//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMonitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupResult
    {
        public int ResultID { get; set; }
        public System.DateTime DatePerformed { get; set; }
        public string Result { get; set; }
        public string Error { get; set; }
        public bool Active { get; set; }
        public int ServerBackup_BackupID { get; set; }
    
        public virtual ServerBackup ServerBackup { get; set; }
    }
}
