//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMonitor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerMonitorEntities : DbContext
    {
        public ServerMonitorEntities()
            : base("name=ServerMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackupResult> BackupResults { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<ServerBackup> ServerBackups { get; set; }
        public virtual DbSet<ServerStatu> ServerStatus { get; set; }
        public virtual DbSet<ServerWarning> ServerWarnings { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
