//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMonitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerWarning
    {
        public int WarningID { get; set; }
        public string WarningCause { get; set; }
        public System.DateTime TimeWarningStart { get; set; }
        public System.DateTime TimeWarningEnd { get; set; }
        public bool Active { get; set; }
        public int Server_ServerID { get; set; }
    
        public virtual Server Server { get; set; }
    }
}
