//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMonitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerStatu
    {
        public int StatusID { get; set; }
        public string CPUUsage { get; set; }
        public string MemoryAvailble { get; set; }
        public string NetworkUsage { get; set; }
        public bool Active { get; set; }
        public int Server_ServerID { get; set; }
    
        public virtual Server Server { get; set; }
    }
}
