//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMonitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerBackup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServerBackup()
        {
            this.BackupResults = new HashSet<BackupResult>();
        }
    
        public int BackupID { get; set; }
        public string Name { get; set; }
        public DateTime ScheduledTime { get; set; }
        public string Frequency { get; set; }
        public string BackupType { get; set; }
        public bool Compression { get; set; }
        public DateTime ExpirationDate { get; set; }
        public string DatabaseName { get; set; }
        public string ServerName { get; set; }
        public bool Active { get; set; }
        public int Server_ServerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackupResult> BackupResults { get; set; }
        public virtual Server Server { get; set; }
    }
}
